### PR TITLE
Support IE Indeterminate checkboxes for "All" option

### PR DESCRIPTION
**Pull request by DanLatimer**
IE handles indeterminate checkboxes "differently", it doesn't fire an
onChange event when a checkbox goes from indeterminate to a determinate
state.

This issue is well documented on the jquery github issue:
https://github.com/jquery/jquery/issues/1698

The generally accepted solution is to use the onClick event instead of the
onChange event. You can see this solution implemented in the google's angular
material design library in their github link here:

https://github.com/angular/material2/issues/3145

I applied a similar approach to normalize the events we listen to for the
indeterminate all checkbox and commented why those things are done in the
code so this issue won't regress.

### CODE REVIEW

**Comment by DanLatimer** [comment]
@leovo2708 I took over fixing the all checkbox not working in IE issue that my collegue submitted a PR for. I've fully tested and this implementation acts the same in both IE and chrome.

**Comment by DanLatimer** [comment]
There are unit tests failing due to our unchceck all being pushed to the end of the event queue. Will address this.

**Comment by leovo2708** [comment]
@DanLatimer Please request a review if you completed

**Comment by mdentremont** [comment]
@leovo2708 It looks like tests are all passing -- the code coverage went down 0.4% due to some refactoring but it should be ready for review

**Comment by mdentremont** [comment]
@leovo2708 We've updated to latest master branch, could you please merge so we can delete our forked repo?

**Pull request closed without merging**
